# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwpuMzRsp3NszF74s3g6LlYacOxfS1mP
"""

def sistema_credito(valRenda, valDespesa, Qtde_Prest, Prestacao):

    # -------------------------
    # R9 e R10 (classificações)
    # -------------------------

    # Renda
    if valRenda >= 10000:
        renda = "Alta"
    else:
        renda = "Baixa"

    # Despesa
    if valDespesa >= 6000:
        despesa = "Alta"
    else:
        despesa = "Baixa"

    # -------------------------
    # R11 e R12
    # -------------------------

    # Quantidade de prestações
    if Qtde_Prest >= 12:
        nPrest = "Alto"
    else:
        nPrest = "Baixo"

    # Valor da prestação
    if Prestacao >= 1000:
        valPrest = "Alto"
    else:
        valPrest = "Baixo"

    # -------------------------
    # R1 a R4 (Cadastro)
    # -------------------------

    if renda == "Alta" and despesa == "Alta":
        cadastro = "Regular"
    elif renda == "Alta" and despesa == "Baixa":
        cadastro = "Bom"
    elif renda == "Baixa" and despesa == "Alta":
        cadastro = "Ruim"
    elif renda == "Baixa" and despesa == "Baixa":
        cadastro = "Regular"

    # -------------------------
    # R5 a R8 (Operação)
    # -------------------------

    if nPrest == "Baixo" and valPrest == "Baixo":
        operacao = "Boa"
    elif nPrest == "Alto" and valPrest == "Baixo":
        operacao = "Boa"
    elif nPrest == "Baixo" and valPrest == "Alto":
        operacao = "Boa"
    elif nPrest == "Alto" and valPrest == "Alto":
        operacao = "Ruim"

    # -------------------------
    # R13 a R16 (Crédito)
    # -------------------------

    if cadastro == "Ruim":
        credito = "Não"
    elif operacao == "Ruim":
        credito = "Não"
    elif cadastro == "Bom" and operacao == "Boa":
        credito = "Sim"
    elif cadastro == "Regular" and operacao == "Boa":
        credito = "Analista"
    else:
        credito = "Indefinido"

    # -------------------------
    # Retorno completo
    # -------------------------

    return {
        "Renda": renda,
        "Despesa": despesa,
        "Cadastro": cadastro,
        "nPrest": nPrest,
        "valPrest": valPrest,
        "Operacao": operacao,
        "Credito": credito
    }


# ==========================
# TESTES (cenários pedidos)
# ==========================

# Caso 1
caso1 = sistema_credito(3000, 6000, 6, 500)

# Caso 2
caso2 = sistema_credito(11000, 4000, 6, 800)

print("CASO 1:", caso1)
print("CASO 2:", caso2)